import 'package:flutter/material.dart';
import 'package:islamy_app/main.dart';

import 'file:///C:/flutter%20projects/islamy_app/lib/Quran/Sura_name_item.dart';

class Quran extends StatelessWidget {
  final List<String> suranames = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
            flex: 1, child: Image.asset('assets/images/quran_top_img.png')),
        Container(
          color: Mythemedata.primarycolor,
          width: double.infinity,
          height: 1,
        ),
        Padding(
          padding: const EdgeInsets.all(2.0),
          child: Text(
            'sura name',
            style: TextStyle(color: Colors.black, fontSize: 25),
          ),
        ),
        Container(
          color: Mythemedata.primarycolor,
          width: double.infinity,
          height: 1,
        ),
        Expanded(
          flex: 3,
          //7tat listview gwa container 3shan ta5od ba2et almsa7a kolha
          child: Container(
            child: ListView.separated(
              itemBuilder: (buildcontext, index) {
                return Sura_name_item(suranames[index], index);
              },
              itemCount: suranames.length,
              separatorBuilder: (BuildContext context, int index) {
                return Container(
                  color: Mythemedata.primarycolor,
                  width: double.infinity,
                  height: 1,
                  margin: EdgeInsets.symmetric(horizontal: 12),
                );
              },
            ),
          ),
        )
      ],
    );
  }
}
